seL4/ci-actions

license-check/README.md
scripts/checkout.sh

make a missing license

---

.github/workflows/push.yml
gitlint/README.md
gitlint/steps.sh
link-check/Dockerfile
link-check/Makefile
link-check/README.md
link-check/action.yml
link-check/steps.sh
scripts/checkout.sh
scripts/fetch-base.sh
scripts/fetch-sel4-tools.sh

Runs https://github.com/raviqqe/liche

Add a repo-local link checker action

---

.github/workflows/push.yml
style/README.md
style/action.yml
style/steps.sh

Add code style action

---

bashisms/steps.sh

fix copy/paster error

---

.github/CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md

add more GitHub setup

---

.github/workflows/deploy-link-check.yml
.github/workflows/deploy-preprocess.yml
.github/workflows/deploy-run-proofs.yml
link-check/action.yml
preprocess/action.yml
run-proofs/action.yml

Docker repo reference must be lower case

---

link-check/Dockerfile

Another upper case docker repo reference

---

scripts/fetch-pr.sh

fetch-pr: make sure to fetch base first

---

scripts/fetch-pr.sh

scripts: create local branch in fetch-pr

---

scripts/fetch-branch.sh

Fix a copy/paste mistake (PR_URL vs URL)

scripts: fetch from correct URL

---

run-proofs/Makefile
scripts/fetch-pr.sh

Don't assume that `BASE_REF` and `REF` have compatible histories.

Simpler fetch

---

preprocess/Makefile
preprocess/test_munge.sh
scripts/fetch-pr.sh

This should fix the preprocess error on PRs from forked repos.

tune PR fetching again

---

run-proofs/README.md
thylint/README.md
thylint/action.yml
thylint/steps.sh
thylint/thylint.py

A GitHub action to lint Isabelle theories for unwanted outer syntax commands like `sorry` or commands that are interactive-only such as `sledgehammer` and `thm`.

thylint action

---

CONTRIBUTING.md
pr-queue/README.md
pr-queue/action.yml
pr-queue/index.js

This adds an action that manages a queue of PRs to be merged via BitBucket by commenting on the PRs to prompt action.

Add PR queue action to queue PRs

---

pr-queue/index.js

Signed-off-by: Curtis Millar <curtis@curtism.me>

trivial: fix syntax

---

.reuse/dep5
pr-queue/package-lock.json
pr-queue/package.json

This ensures that the package dependencies are correctly described so that actions provides them in the runtime,

Make PR Queue node package

---

pr-queue/index.js

This fixes a bug and also tries to reduce the number of queries made to GitHub each time this is run.

Fixes for PR queue

---

.github/workflows/isabelle-mirror.yml
bashisms/action.yml
git-diff-check/action.yml
gitlint/action.yml
isabelle-mirror/README.md
isabelle-mirror/action.yml
isabelle-mirror/bin/hg
isabelle-mirror/bin/hg-git
isabelle-mirror/bin/hg-system
isabelle-mirror/bin/im-env
isabelle-mirror/bin/im-fetch-downstream-git
isabelle-mirror/bin/im-fetch-upstream-hg
isabelle-mirror/bin/im-main
isabelle-mirror/bin/im-mirror-anywhere
isabelle-mirror/bin/im-mirror-here
isabelle-mirror/bin/im-push-downstream-git
isabelle-mirror/bin/im-setup
isabelle-mirror/steps.sh
license-check/action.yml
link-check/action.yml
preprocess/action.yml
run-proofs/action.yml
scripts/hg-system
style/action.yml
thylint/action.yml

This action mirrors the upstream hg Isabelle repositories to the GitHub version in the seL4 org. The scripts that do the actual work are originally by @mbrcknl

Isabelle mirror

---

preprocess/Makefile
preprocess/action.yml
preprocess/steps.sh

After this is merged, we can add "MCS" to the matrix build in the seL4 repo.

Add MCS preprocessing

---

link-check/steps.sh

The link checker was reporting broken links, but not failing for them. This PR fixes that.

Link check fix

---

.github/workflows/deploy-sel4test-hw.yml
seL4-platforms/builds.py
seL4-platforms/platforms.py
seL4-platforms/platforms.yml
sel4test-hw/Dockerfile
sel4test-hw/Makefile
sel4test-hw/README.md
sel4test-hw/action.yml
sel4test-hw/build.py
sel4test-hw/builds.yml
sel4test-hw/steps.sh

This adds an action for the hardware builds in sel4test, leaving images for artefact upload.

sel4test hardware builds

---

cparser-run/steps.sh
sel4test-hw/steps.sh
sel4test-sim/steps.sh
tutorials/steps.sh

This makes it possible to merge multiple PRs and eventually converge again. Otherwise the tests can only ever check one local change.

manifests: use master.xml for tests by default

---

rump-hello/Dockerfile
rump-hello/Makefile
rump-hello/README.md
rump-hello/action.yml
rump-hello/build.py
rump-hello/builds.yml
rump-hello/steps.sh
seL4-platforms/builds.py

GitHub action for `rumprun-hello`.

Rumprun tests

---

.github/workflows/deploy-camkes-test.yml
.github/workflows/deploy-rumprun.yml
.github/workflows/deploy-tutorials.yml
camkes-test/Dockerfile
camkes-test/Makefile
camkes-test/README.md
camkes-test/action.yml
camkes-test/build.py
camkes-test/builds.yml
camkes-test/steps.sh
seL4-platforms/builds.py
tutorials/build.py
tutorials/builds.yml
tutorials/steps.sh

includes simulation runs and hardware builds, but not hardware runs yet (blocked on machine queue)

add CAmkES test action

---

camkes-vm/Dockerfile
camkes-vm/Makefile
camkes-vm/README.md
camkes-vm/action.yml
camkes-vm/build.py
camkes-vm/builds.yml
camkes-vm/steps.sh
seL4-platforms/builds.py

These mirror the Bamboo CAmkES VM tests.

CAmkES VM builds

---

camkes-vm/build.py
camkes-vm/builds.yml
march-of-platform/README.md
march-of-platform/action.yml
march-of-platform/march.py
march-of-platform/steps.sh
seL4-platforms/builds.py
seL4-platforms/platforms.py
seL4-platforms/platforms.yml
sel4test-hw-run/README.md
sel4test-hw-run/action.yml
sel4test-hw-run/build.py
sel4test-hw-run/builds.yml
sel4test-hw-run/post-steps.sh
sel4test-hw-run/steps.sh
sel4test-hw/build.py
sel4test-hw/builds.yml

This action downloads previously built images and runs them on specified hardware platforms using the machine queue at UNSW.
The boards and the machine queue are still not entirely stable, but the logic is there and things mostly work.

sel4test hardware runs

---

aws-proofs/action.yml
aws-proofs/steps.sh
aws-proofs/vm-steps.sh
l4v-deploy/README.md
l4v-deploy/action.yml
l4v-deploy/common.py
l4v-deploy/seL4-pp
l4v-deploy/staging-manifest
l4v-deploy/steps.sh
scripts/checkout-manifest.sh

GH action to deploy verification manifest changes after successful proof run or preprocess run.
For now only the deployment after proof run is implemented, the code for preprocess run after seL4 master commit is not yet tested.

deploy l4v manifests

---

camkes-test/Dockerfile
camkes-test/steps.sh
camkes-vm/Dockerfile
camkes-vm/steps.sh
cparser-run/Dockerfile
cparser-run/steps.sh
preprocess/Dockerfile
repo-checkout/steps.sh
rump-hello/Dockerfile
rump-hello/steps.sh
run-proofs/steps.sh
scripts/fetch-branches.sh
sel4test-hw/Dockerfile
sel4test-hw/steps.sh
sel4test-sim/Dockerfile
sel4test-sim/steps.sh
tutorials/Dockerfile
tutorials/steps.sh

This factors out the PR fetching code into its own script snippet and unifies script PATH and directory for the corresponding Docker files.

all manifest actions: test simultaneous PRs

---

aws-proofs/README.md
camkes-hw/README.md
camkes-hw/action.yml
camkes-hw/build.py
camkes-hw/builds.yml
camkes-hw/post-steps.sh
camkes-hw/steps.sh
camkes-test/build.py
camkes-test/builds.yml
scripts/setup-hw-ssh.sh
seL4-platforms/builds.py
sel4test-hw-run/README.md
sel4test-hw-run/post-steps.sh
sel4test-hw-run/steps.sh

This action runs the images produced by the `camkes-test` action on hardware.
See also seL4/camkes-tool#88

CAmkES hardware tests

---

camkes-hw/post-steps.sh
camkes-hw/steps.sh
camkes-vm-hw/post-steps.sh
camkes-vm-hw/steps.sh
scripts/hw-post-steps.sh
scripts/hw-steps.sh
sel4bench-hw/post-steps.sh
sel4bench-hw/steps.sh
sel4test-hw-run/post-steps.sh
sel4test-hw-run/steps.sh

The commands to start up and shut down hardware tests are the same
for each test and only differ in which python build script they
invoke. This commit factors out the common parts.

hw test: factor out common steps

---

rump-hello-hw/README.md
rump-hello-hw/action.yml
rump-hello-hw/build.py
rump-hello-hw/builds.yml
rump-hello-hw/post-steps.sh
rump-hello-hw/steps.sh
rump-hello/build.py

The last of the missing hardware test runs from Bamboo..

rump-hello-hw: hardware run for the rumprun tests

---

seL4-platforms/platforms.yml
sel4test-hw-matrix/README.md
sel4test-hw-matrix/action.yml
sel4test-hw-matrix/build.py
sel4test-hw-matrix/builds.yml
sel4test-hw-matrix/steps.sh
sel4test-hw/build.py

This avoids replicating the run matrix in individual workflow files.
Closes #168

generate hw run matrix automatically

---

bashisms/README.md
bashisms/action.yml
git-diff-check/README.md
git-diff-check/action.yml
gitlint/README.md
gitlint/action.yml
style/README.md
style/action.yml
thylint/README.md
thylint/action.yml

This enables further actions to be used on private repos.

pass through PA tokens for private repo access

---

repo-checkout/action.yml

fix copy/paste legacy and use a proper desrciption.

doc: fix description

---

seL4-platforms/platforms.yml

See https://github.com/seL4/seL4/pull/829

platforms: add maaxboard

---

.github/workflows/deploy-camkes-test.yml
.github/workflows/deploy-camkes-unit.yml
.github/workflows/deploy-camkes-vm.yml
.github/workflows/deploy-cparser-builder.yml
.github/workflows/deploy-cparser-run.yml
.github/workflows/deploy-link-check.yml
.github/workflows/deploy-preprocess.yml
.github/workflows/deploy-rumprun.yml
.github/workflows/deploy-run-proofs.yml
.github/workflows/deploy-sel4bench.yml
.github/workflows/deploy-sel4test-hw.yml
.github/workflows/deploy-sel4test-sim.yml
.github/workflows/deploy-tutorials.yml

This helps to distinguish the workflows in the UI for manual triggers.

github: make workflow names distinct

---

sel4bench/build.py

See #203 and seL4/sel4bench#20 for background.

sel4bench: remove HARDWARE and FAULT for hifive

---

bashisms/README.md

(no change in checkbashism.pl script)

bashims: bump devscripts version

---

.github/workflows/deploy-camkes-test.yml
.github/workflows/deploy-camkes-unit.yml
.github/workflows/deploy-camkes-vm.yml
.github/workflows/deploy-cparser-builder.yml
.github/workflows/deploy-cparser-run.yml
.github/workflows/deploy-link-check.yml
.github/workflows/deploy-preprocess.yml
.github/workflows/deploy-rumprun.yml
.github/workflows/deploy-run-proofs.yml
.github/workflows/deploy-sel4bench.yml
.github/workflows/deploy-sel4test-hw.yml
.github/workflows/deploy-sel4test-sim.yml
.github/workflows/deploy-tutorials.yml

Upgrade necessary to use node16 actions + new GitHub output/set-state mechanisms.

github: bump docker + trigger action versions

---

cparser-run/builds.yml
seL4-platforms/platforms.yml

See https://github.com/seL4/seL4/pull/818

platforms: add qemu-riscv-virt

---

.github/workflows/deploy-webserver.yml
webserver-hw/README.md
webserver-hw/action.yml
webserver-hw/build.py
webserver-hw/builds.yml
webserver-hw/post-steps.sh
webserver-hw/steps.sh
webserver/Dockerfile
webserver/Makefile
webserver/README.md
webserver/action.yml
webserver/build.py
webserver/builds.yml
webserver/steps.sh

Contains:
- build action
- hardware run action
- docker image deployment for build action environment

CI action for seL4  web server demo app

---

seL4-platforms/platforms.yml

- new odroid_c2 in service
- zcu106 currently having problems

update available boards

---

scripts/get-prs

GITHUB_TOKEN is not available implicitly

scripts: use explicit INPUT_TOKEN

---

bashisms/README.md
camkes-test/build.py
l4v-deploy/common.py
seL4-platforms/builds.py
sel4test-sim/build.py
tutorials/build.py

Cleaning up the CI sources a little.
- remove unused or duplicate imports
- not x in S -> x not in S
Also (separate commit) update bashims link; no changes to upstream script.

Fix most python lints

---

seL4-platforms/platforms.yml

#263 was a bit too optimistic.

platforms: imx8mq does not support MCS after all

---

seL4-platforms/platforms.yml

Cannot successfully run seL4test in release mode, only debug mode works currently. Disable until I figure out the issue.

platforms: disable RPi4

---

seL4-platforms/platforms.yml

(temporary network problems, should come back in a week or so)

platforms: temporarily remove haswell4 machine

---

sel4test-hw/build.py

Until https://github.com/seL4/seL4/issues/1160 is resolved.

sel4test-hw: skip riscv+clang+smp+release

---

seL4-platforms/platforms.yml

Until https://github.com/seL4/ci-actions/pull/310 is merged.

platforms: disable MaaXBoard temporarily

---

bashisms/README.md

bashisms: bump devscripts version

---

seL4-platforms/platforms.yml

the benchmarking project is concluded.

platforms: imx8mm available again for CI

---

dashboard/gen-dashboard.py

- use new badge link format (old one produces broken links/images)
- add config for new repos and workflows (microkit, rust, etc)

update dashboard script

---

license-check/steps.sh

Version 4 (released yesterday) seems to be broken.

license-check: pin reuse version

---

js/node_modules/.package-lock.json
js/node_modules/undici/lib/core/constants.js
js/node_modules/undici/lib/core/util.js
js/node_modules/undici/lib/fetch/body.js
js/node_modules/undici/lib/fetch/index.js
js/node_modules/undici/lib/fetch/util.js
js/node_modules/undici/lib/handler/RedirectHandler.js
js/node_modules/undici/package.json
js/package-lock.json

Fixes https://github.com/seL4/ci-actions/security/dependabot/21
Dependency update only (via `npm audit --fix`)

js: update dependencies

---

bashisms/README.md
scripts/checkbashisms

bashisms check: update to v2.52.2

---

sel4test-hw/build.py

With some luck https://github.com/seL4/seL4/pull/871 fixes all of these.
Should only be merged after this is confirmed on https://github.com/seL4/seL4/pull/871

sel4test: enable SMP tests

---

seL4-platforms/platforms.yml

After support in seL4/seL4#1420 and seL4/seL4_tools#222

platforms: enable SMP tests on RPI4

---

seL4-platforms/platforms.yml

Due to discussion in https://github.com/seL4/ci-actions/pull/385.

platforms.yml: fix march for Cheshire and Ariane

---

.github/workflows/push.yml
.linkcheck-ignore.yml
link-check/steps.sh

Handle an empty list of ignore patterns, and print the files to be checked.

link-check: handle empty list of ignore file patterns 

---

seL4-platforms/platforms.yml

This reverts commit a609f1a53beec4af2fdad8455ead6114bd694f29.
https://github.com/seL4/sel4bench/pull/55
https://github.com/seL4/ci-actions/pull/388#issuecomment-2728308843

Revert "platforms.yml: remove cheshire support"
